CREATE USER pbr;
ALTER ROLE pbr WITH PASSWORD 'secret';

CREATE DATABASE pbr_dev OWNER pbr;
GRANT ALL PRIVILEGES ON DATABASE pbr_dev TO pbr;

CREATE DATABASE pbr_test OWNER pbr;
GRANT ALL PRIVILEGES ON DATABASE pbr_test TO pbr;
